import type { SourceConfig } from "./types";

const defaultUa = "ShareChatAPMTrendingTags/1.0 (+https://sharechat.com; Bharat-Hindi trend prototype)";

export const SOURCE_CONFIGS: SourceConfig[] = [
  {
    name: "Google Trends India",
    sourceType: "search_demand",
    urls: ["https://trends.google.com/trending/rss?geo=IN"],
    reliabilityWeight: 0.85,
    purpose: "India search-demand seed. High for demand, not facts.",
    userAgent: `${defaultUa} GoogleTrendsFetcher`,
    enabled: true,
    languageHint: "mixed",
    indiaFilteredByDesign: true,
  },
  {
    name: "Dainik Bhaskar",
    sourceType: "hindi_news",
    urls: ["https://www.bhaskar.com/rss-feed/1061/"],
    reliabilityWeight: 0.75,
    purpose: "Hindi heartland news.",
    userAgent: `${defaultUa} BhaskarRSS`,
    enabled: true,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "Dainik Jagran",
    sourceType: "hindi_news",
    urls: [
      "https://rss.jagran.com/rss/news/national.xml",
      "https://rss.jagran.com/rss/cricket/headlines.xml",
      "https://rss.jagran.com/rss/entertainment/bollywood.xml",
      "https://rss.jagran.com/rss/news/world.xml",
    ],
    reliabilityWeight: 0.75,
    purpose: "Disabled: Jagran RSS is currently returning HTTP 500 from the public national feed in this environment. Kept for easy re-enable if publisher feed stabilizes.",
    userAgent: `${defaultUa} JagranRSS`,
    enabled: false,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "Amar Ujala",
    sourceType: "hindi_news",
    urls: ["https://www.amarujala.com/rss/breaking-news.xml"],
    reliabilityWeight: 0.75,
    purpose: "North India and hill-state coverage.",
    userAgent: `${defaultUa} AmarUjalaRSS`,
    enabled: true,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "Live Hindustan",
    sourceType: "hindi_news",
    urls: [
      "https://www.livehindustan.com/rss/national.xml",
      "https://www.livehindustan.com/rss/news.xml",
      "https://www.livehindustan.com/rss/uttar-pradesh.xml",
    ],
    reliabilityWeight: 0.75,
    purpose: "Hindi national/state/category news. Retained with fallbacks, but disabled while publisher RSS returns repeated 503s.",
    userAgent: `${defaultUa} LiveHindustanRSS`,
    enabled: false,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "NDTV Hindi",
    sourceType: "hindi_news",
    urls: ["https://feeds.feedburner.com/ndtvkhabar-latest"],
    reliabilityWeight: 0.75,
    purpose: "NDTV Hindi national news via Feedburner. Strong India coverage.",
    userAgent: `${defaultUa} NDTVHindiRSS`,
    enabled: true,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "India TV News",
    sourceType: "hindi_news",
    urls: ["https://www.indiatvnews.com/rssfeed/india.xml"],
    reliabilityWeight: 0.7,
    purpose: "India TV news RSS. Useful for national and Hindi-belt validation.",
    userAgent: `${defaultUa} IndiaTVRSS`,
    enabled: true,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "Hindustan Times",
    sourceType: "national_news",
    urls: ["https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml"],
    reliabilityWeight: 0.7,
    purpose: "Hindustan Times India news. English but strong India coverage for validation.",
    userAgent: `${defaultUa} HindustanTimesRSS`,
    enabled: true,
    languageHint: "en",
  },
  {
    name: "News18 Hindi",
    sourceType: "hindi_news",
    urls: [
      "https://hindi.news18.com/rss/khabar/nation.xml",
      "https://hindi.news18.com/rss/khabar/latest.xml",
      "https://hindi.news18.com/rss/khabar/uttar-pradesh.xml",
    ],
    reliabilityWeight: 0.7,
    purpose: "Disabled: public RSS endpoints return HTTP 403 in this environment. Kept as documented future source if API/RSS access is permitted.",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
    enabled: false,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "The Hindu National",
    sourceType: "national_news",
    urls: ["https://www.thehindu.com/news/national/feeder/default.rss"],
    reliabilityWeight: 0.65,
    purpose: "South India and national-significance validation. Not Hindi-native; validation only.",
    userAgent: `${defaultUa} TheHinduRSS`,
    enabled: true,
    languageHint: "en",
  },
  {
    name: "PIB Hindi",
    sourceType: "official_government",
    urls: [
      "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=2",
      "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=2&Regid=3",
      "https://ddnews.gov.in/hi/feed/",
    ],
    reliabilityWeight: 0.95,
    purpose: "Disabled: PIB public RSS returns HTTP 403 and DD News feed parsing is unreliable in this environment. Production should use PIB/API access or a licensed official news feed.",
    userAgent: `${defaultUa} PIBHindiRSS`,
    enabled: false,
    languageHint: "hi",
    official: true,
    indiaFilteredByDesign: true,
    categoryHint: "government",
  },
  {
    name: "RBI",
    sourceType: "official_finance",
    urls: [
      "https://rbi.org.in/pressreleases_rss.xml",
      "https://rbi.org.in/notifications_rss.xml",
      "https://rbi.org.in/speeches_rss.xml",
    ],
    reliabilityWeight: 0.95,
    purpose: "Finance and banking authority. Neutral, no sensational wording.",
    userAgent: `${defaultUa} RBIRSS`,
    enabled: true,
    languageHint: "en",
    official: true,
    indiaFilteredByDesign: true,
    categoryHint: "finance",
  },
  {
    name: "IMD",
    sourceType: "weather",
    urls: [
      "https://wttr.in/Delhi?format=j1",
      "https://wttr.in/Mumbai?format=j1",
      "https://wttr.in/Chennai?format=j1",
      "https://wttr.in/Kolkata?format=j1",
      "https://wttr.in/Bengaluru?format=j1",
      "https://wttr.in/Hyderabad?format=j1",
      "https://wttr.in/Lucknow?format=j1",
      "https://wttr.in/Jaipur?format=j1",
    ],
    reliabilityWeight: 0.75,
    purpose: "Weather signals for major Indian cities via wttr.in free JSON. Detects heat waves, heavy rain, and storms.",
    userAgent: `${defaultUa} WeatherFetcher`,
    enabled: true,
    indiaFilteredByDesign: true,
    categoryHint: "weather",
  },
  {
    name: "SACHET",
    sourceType: "public_safety",
    urls: ["https://sachet.ndma.gov.in/CapFeed"],
    reliabilityWeight: 0.95,
    purpose: "Public-safety and disaster alerts. Calm and informative tone.",
    userAgent: `${defaultUa} SACHETCAP`,
    enabled: true,
    official: true,
    indiaFilteredByDesign: true,
    categoryHint: "public_safety",
  },
  {
    name: "YouTube",
    sourceType: "video",
    urls: ["https://www.googleapis.com/youtube/v3/videos", "https://www.googleapis.com/youtube/v3/search"],
    reliabilityWeight: 0.7,
    purpose: "Popular India videos and selective Hindi candidate search when YOUTUBE_API_KEY exists.",
    userAgent: `${defaultUa} YouTubeDataAPI`,
    enabled: Boolean(process.env.YOUTUBE_API_KEY),
    requiresKey: "YOUTUBE_API_KEY",
    languageHint: "mixed",
  },
  {
    name: "Calendarific",
    sourceType: "festival_calendar",
    urls: ["https://calendarific.com/api/v2/holidays"],
    reliabilityWeight: 0.55,
    purpose: "Festival date lookup and cultural pre-seeding when CALENDARIFIC_API_KEY exists.",
    userAgent: `${defaultUa} Calendarific`,
    enabled: Boolean(process.env.CALENDARIFIC_API_KEY),
    requiresKey: "CALENDARIFIC_API_KEY",
    categoryHint: "festival",
  },
  {
    name: "GoodReturns Gold Rates",
    sourceType: "national_news",
    urls: ["https://www.goodreturns.in/gold-rates/"],
    reliabilityWeight: 0.55,
    purpose: "Optional utility/bazaar evidence for gold and silver rate topics. Production should use licensed commodity feeds or trusted price APIs.",
    userAgent: `${defaultUa} UtilityGoldRates`,
    enabled: true,
    languageHint: "en",
    categoryHint: "finance",
  },
  {
    name: "GoodReturns Petrol Prices",
    sourceType: "national_news",
    urls: ["https://www.goodreturns.in/petrol-price.html"],
    reliabilityWeight: 0.55,
    purpose: "Optional utility/bazaar evidence for petrol/diesel daily rate topics. Production should use OMC/partner feeds or official city-level fuel data.",
    userAgent: `${defaultUa} UtilityFuelRates`,
    enabled: true,
    languageHint: "en",
    categoryHint: "finance",
  },
  {
    name: "Economic Times Fuel Prices",
    sourceType: "national_news",
    urls: ["https://economictimes.indiatimes.com/wealth/fuelprices/petrol"],
    reliabilityWeight: 0.55,
    purpose: "Optional utility/bazaar evidence for fuel prices; parsed defensively and never required for API success.",
    userAgent: `${defaultUa} UtilityFuelRatesET`,
    enabled: true,
    languageHint: "en",
    categoryHint: "finance",
  },
  {
    name: "Internal Festival Calendar",
    sourceType: "festival_calendar",
    urls: ["src/data/indian-festivals.json"],
    reliabilityWeight: 0.55,
    purpose: "Safe internal Bharat/Hindi festival and devotional seed list.",
    userAgent: `${defaultUa} InternalFestivalJSON`,
    enabled: true,
    categoryHint: "festival",
    languageHint: "hi",
  },
  {
    name: "Reddit",
    sourceType: "social_experimental",
    urls: [
      "https://www.reddit.com/r/india/hot.json",
      "https://www.reddit.com/r/bollywood/hot.json",
      "https://www.reddit.com/r/cricket/hot.json",
      "https://www.reddit.com/r/IndianDankMemes/hot.json",
    ],
    reliabilityWeight: 0.35,
    purpose: "Disabled: Reddit public JSON now frequently requires OAuth. Kept for future OAuth integration.",
    userAgent: `${defaultUa} RedditPublicJSON`,
    enabled: false,
    languageHint: "en",
  },
  {
    name: "India Social Trends",
    sourceType: "social_experimental",
    urls: ["https://www.patrika.com/rss/india-news.xml"],
    reliabilityWeight: 0.45,
    purpose: "Patrika Hindi RSS used as a no-key India social/viral replacement for blocked Reddit JSON.",
    userAgent: `${defaultUa} IndiaSocialTrends`,
    enabled: true,
    languageHint: "hi",
    hindiNative: true,
  },
  {
    name: "Roanuz",
    sourceType: "sports",
    urls: ["https://api.sports.roanuz.com"],
    reliabilityWeight: 0.85,
    purpose: "Optional live cricket facts if ROANUZ_API_KEY exists. Never invent score/toss/wicket without a trusted source.",
    userAgent: `${defaultUa} RoanuzCricket`,
    enabled: Boolean(process.env.ROANUZ_API_KEY),
    requiresKey: "ROANUZ_API_KEY",
    categoryHint: "sports",
  },
];

export function getSourceConfig(name: string): SourceConfig | undefined {
  return SOURCE_CONFIGS.find((source) => source.name === name);
}
