import type { SourceType, TrendCategory } from "./types";

export const CACHE_WINDOW_MINUTES = 30 as const;
export const CACHE_WINDOW_MS = CACHE_WINDOW_MINUTES * 60 * 1000;
export const CACHE_NOTE =
  "The 30-minute cache window is not arbitrary. During research, I observed ShareChat's own trending feed directly — only 2 of 4 tags changed over a 30-minute window. Trends do not move second-by-second. The cache matches the actual refresh cadence of the product I am trying to improve.";

export function toIndiaIsoString(date = new Date()): string {
  const istOffsetMs = 5.5 * 60 * 60 * 1000;
  return new Date(date.getTime() + istOffsetMs).toISOString().replace("Z", "+05:30");
}

export const ASSUMPTIONS = [
  "Prototype uses external validation because ShareChat internal data is unavailable.",
  "Production ranking should use ShareChat searches, posts, shares, comments, watch time, tag taps, creator velocity, and content inventory.",
  "Content inventory status is estimated in the prototype.",
  "Production success metrics should include trend CTR, post-tap watch time, detail-page dwell time, content creation from tag, language-match rate, hide/report rate, and duplicate rate.",
  "Language-match rate is especially important because ShareChat is language-first, not just India-first.",
];

export const INDIA_TERMS = ["india", "bharat", "hindustan", "desh", "भारतीय", "भारत", "इंडिया"];

export const HINDI_HINTS = [
  "हिंदी",
  "भारत",
  "देश",
  "बारिश",
  "चुनाव",
  "सरकार",
  "योजना",
  "क्रिकेट",
  "फिल्म",
  "भक्ति",
  "पूजा",
  "मंदिर",
  "मौसम",
  "नौकरी",
  "परीक्षा",
  "राशिफल",
  "वायरल",
  "bhojpuri",
  "bollywood",
  "sarkari",
  "naukri",
  "yojana",
  "cricket",
  "mandir",
  "bhakti",
  "puja",
];

export const COMMON_ACRONYMS_ALLOWLIST = [
  "IPL",
  "RBI",
  "UPI",
  "NEET",
  "JEE",
  "CBSE",
  "NTA",
  "IMD",
  "BJP",
  "IND",
  "AUS",
  "MI",
  "CSK",
  "WPL",
  "ODI",
  "T20",
  "PM",
  "CM",
];

export const INDIAN_CITIES_STATES = [
  "Delhi",
  "Mumbai",
  "Lucknow",
  "Kanpur",
  "Patna",
  "Jaipur",
  "Indore",
  "Bhopal",
  "Varanasi",
  "Prayagraj",
  "Noida",
  "Ghaziabad",
  "Gurugram",
  "Ranchi",
  "Raipur",
  "Ahmedabad",
  "Surat",
  "Pune",
  "Nagpur",
  "Hyderabad",
  "Chennai",
  "Bengaluru",
  "Kolkata",
  "Bihar",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Rajasthan",
  "Maharashtra",
  "Jharkhand",
  "Chhattisgarh",
  "Gujarat",
  "Uttarakhand",
  "Himachal",
  "Haryana",
  "Punjab",
  "Delhi NCR",
  "Bengal",
  "Odisha",
  "Assam",
  "Kerala",
  "Tamil Nadu",
  "Karnataka",
  "Telangana",
  "Andhra Pradesh",
  "दिल्ली",
  "मुंबई",
  "लखनऊ",
  "कानपुर",
  "पटना",
  "जयपुर",
  "इंदौर",
  "भोपाल",
  "वाराणसी",
  "प्रयागराज",
  "नोएडा",
  "गाजियाबाद",
  "गुरुग्राम",
  "रांची",
  "रायपुर",
  "अहमदाबाद",
  "सूरत",
  "पुणे",
  "नागपुर",
  "हैदराबाद",
  "चेन्नई",
  "बेंगलुरु",
  "कोलकाता",
  "बिहार",
  "उत्तर प्रदेश",
  "मध्य प्रदेश",
  "राजस्थान",
  "महाराष्ट्र",
  "झारखंड",
  "छत्तीसगढ़",
  "गुजरात",
  "उत्तराखंड",
  "हिमाचल",
  "हरियाणा",
  "पंजाब",
  "ओडिशा",
  "असम",
  "केरल",
  "तमिलनाडु",
  "कर्नाटक",
  "तेलंगाना",
  "आंध्र प्रदेश",
];

export const INDIAN_ENTITIES = [
  ...INDIAN_CITIES_STATES,
  "Narendra Modi",
  "Modi",
  "PM Modi",
  "Amit Shah",
  "Yogi",
  "Virat Kohli",
  "Kohli",
  "Rohit Sharma",
  "Rohit",
  "MS Dhoni",
  "Dhoni",
  "Sachin",
  "BCCI",
  "Team India",
  "India",
  "Bharat",
  "RBI",
  "UPI",
  "PIB",
  "IMD",
  "NDMA",
  "SACHET",
  "IPL",
  "WPL",
  "Bollywood",
  "Bhojpuri",
  "CBSE",
  "NTA",
  "UPSC",
  "SSC",
  "NEET",
  "JEE",
  "मोदी",
  "योगी",
  "विराट कोहली",
  "रोहित शर्मा",
  "धोनी",
  "टीम इंडिया",
  "बीसीसीआई",
  "आरबीआई",
  "यूपीआई",
  "पीआईबी",
  "आईएमडी",
  "एनडीएमए",
  "बॉलीवुड",
  "भोजपुरी",
];

export const SPAM_BLOCKLIST = [
  "free recharge",
  "earn money",
  "hack",
  "trick 2026",
  "lottery",
  "shocking",
  "leaked video",
  "click here",
  "paisa kamao",
  "paise kamao",
  "betting",
  "casino",
  "telegram link",
  "फ्री रिचार्ज",
  "पैसा कमाओ",
  "लॉटरी",
  "टेलीग्राम लिंक",
  "हैक",
];

export const ADULT_BLOCKLIST = [
  "xxx",
  "porn",
  "nude",
  "sex",
  "hot video",
  "leaked mms",
  "पोर्न",
  "न्यूड",
  "सेक्स",
  "एमएमएस",
];

export const SENSITIVE_REVIEW_KEYWORDS = [
  "communal",
  "riot",
  "riots",
  "mob",
  "lynching",
  "murder",
  "suicide",
  "rape",
  "blast",
  "terror",
  "terrorist",
  "religious violence",
  "hate speech",
  "fake news",
  "death",
  "dead",
  "killed",
  "दंगा",
  "हत्या",
  "आत्महत्या",
  "रेप",
  "बलात्कार",
  "मौत",
  "मर्डर",
  "धमाका",
  "आतंक",
  "सांप्रदायिक",
  "नफरत",
];

export const BHARAT_RELEVANT_CATEGORIES: TrendCategory[] = [
  "sports",
  "festival",
  "devotional",
  "weather",
  "government",
  "finance",
  "education",
  "jobs",
  "movies",
  "music",
  "entertainment",
  "local",
  "public_safety",
];

export const OFFICIAL_SOURCE_TYPES: SourceType[] = [
  "official_government",
  "official_finance",
  "weather",
  "public_safety",
];

export const HINDI_NEWS_SOURCE_NAMES = ["Dainik Bhaskar", "Dainik Jagran", "Amar Ujala", "Live Hindustan"];

export const SOURCE_FAMILY: Record<string, string> = {
  "Dainik Bhaskar": "hindi-news-bhaskar",
  "Dainik Jagran": "hindi-news-jagran",
  "Amar Ujala": "hindi-news-amar-ujala",
  "Live Hindustan": "hindi-news-live-hindustan",
  "The Hindu National": "the-hindu",
  "Google Trends India": "google-trends",
  "PIB Hindi": "pib",
  RBI: "rbi",
  IMD: "imd",
  SACHET: "sachet",
  YouTube: "youtube",
  Calendarific: "calendarific",
  "Internal Festival Calendar": "internal-festival-calendar",
  Reddit: "reddit",
  Roanuz: "roanuz",
};

export const CATEGORY_BASELINES: Record<TrendCategory, number> = {
  sports: 2,
  news: 2,
  entertainment: 2,
  finance: 1,
  weather: 1,
  politics: 2,
  devotional: 1,
  festival: 1,
  education: 1,
  jobs: 1,
  viral: 2,
  public_safety: 1,
  government: 1,
  technology: 2,
  local: 1,
  movies: 2,
  music: 2,
};

export const CATEGORY_KEYWORDS: Record<TrendCategory, string[]> = {
  sports: ["cricket", "match", "ipl", "wpl", "ind vs", "aus", "kohli", "rohit", "dhoni", "wicket", "fifty", "century", "toss", "score", "क्रिकेट", "मैच", "विकेट", "शतक", "अर्धशतक"],
  weather: ["rain", "बारिश", "monsoon", "heatwave", "लू", "flood", "बाढ़", "cyclone", "चक्रवात", "imd", "मौसम", "अलर्ट"],
  finance: ["rbi", "repo rate", "inflation", "upi", "bank", "banking", "nbfc", "monetary policy", "रेपो रेट", "महंगाई", "बैंक", "यूपीआई", "सोना", "चांदी", "सोने", "gold rate", "gold price", "silver rate", "petrol", "diesel", "पेट्रोल", "डीजल", "lpg", "एलपीजी", "cng", "सीएनजी", "सिलेंडर", "कीमत", "भाव", "रेट", "टमाटर", "प्याज"],
  government: ["pib", "government scheme", "yojana", "योजना", "ministry", "संसद", "cabinet", "budget", "सरकार", "मंत्रालय"],
  festival: ["diwali", "holi", "chhath", "navratri", "sawan", "eid", "raksha", "janmashtami", "दिवाली", "दीपावली", "होली", "छठ", "नवरात्रि", "ईद", "रक्षा", "जन्माष्टमी", "दशहरा"],
  devotional: ["puja", "bhakti", "mandir", "temple", "aarti", "hanuman", "shiv", "krishna", "ram", "मंदिर", "पूजा", "भक्ति", "आरती", "हनुमान", "शिव", "कृष्ण", "राम"],
  entertainment: ["ott", "actor", "actress", "celebrity", "viral video", "entertainment", "मनोरंजन", "एक्टर", "एक्ट्रेस"],
  movies: ["film", "movie", "trailer", "bollywood", "bhojpuri", "फिल्म", "ट्रेलर", "बॉलीवुड", "भोजपुरी", "सिनेमा"],
  music: ["song", "music", "गाना", "गीत", "सॉन्ग", "भजन"],
  education: ["exam", "result", "admit card", "neet", "jee", "cbse", "upsc", "nta", "परीक्षा", "रिजल्ट", "एडमिट कार्ड"],
  jobs: ["sarkari naukri", "job", "jobs", "ssc", "railway recruitment", "नौकरी", "सरकारी नौकरी", "भर्ती"],
  public_safety: ["alert", "warning", "disaster", "flood warning", "cyclone alert", "ndma", "sachet", "चेतावनी", "आपदा", "सुरक्षा"],
  technology: ["iphone", "openai", "ai", "whatsapp", "instagram", "tech launch", "smartphone", "app", "टेक", "स्मार्टफोन", "ऐप"],
  politics: ["election", "bjp", "congress", "minister", "cm", "pm", "चुनाव", "बीजेपी", "कांग्रेस", "मुख्यमंत्री", "प्रधानमंत्री"],
  news: ["breaking", "latest", "news", "खबर", "समाचार", "ताजा"],
  viral: ["viral", "trend", "meme", "मीम", "वायरल", "ट्रेंड"],
  local: ["district", "city", "local", "जिला", "शहर", "गांव", "स्थानीय"],
};
